### ISSUE TITLE
Genius TCAD Open error: Assertion failure

### ISSUE THREAD

**Issue by yoshiji-kobayashi** [lutherthecat/Genius-TCAD-Open#3]
HI!
I could install Genius-TCAD-Open to my system ubuntu12.04 without error.
But the program stopped and showed the following error message.
Error message:   Assertion failure at ../../src/utlis/sync-file.cc:77
I use gcc-4.6.3 ,petsc-3.1-p8 ,cgnslib-2.5.2 and vtk-5.4.
Could you help me?

**Comment by lutherthecat** [comment]
Looking in the code, it looks like it may be an issue with the file being opened.  You may want to file an issue with the original project, cogenda/Genius-TCAD-Open

**Comment by yoshiji-kobayashi** [comment]
Thanks for your comment.

**Comment by lutherthecat** [comment]
Looks like you were able to fix the issue.
